### PR TITLE
Add script to get emails of editors

### PR DESCRIPTION
**Pull request by hargup**
This script needs to be run with the following command
```
mysql -u metakgp_user --database=metakgp_wiki_db --password="password"< get_editor_emails.sql >emails.csv
```
(replace "password" with the actual password)

### CODE REVIEW

**Comment by icyflame** [comment]
@hargup Can you please re-commit with the right author and email? It is not associated with your account. Thanks! Also, I don't think `hargup@metakgp.org` is a real email ID?

**Comment by hargup** [comment]
> I don't think hargup@metakgp.org is a real email ID,

Yeah, it isn't, I don't know how that came in.

**Comment by icyflame** [comment]
Also, @hargup could you maybe create a bash wrapper for this? And put the documentation that you have given in your first comment to the top portion of the bash wrapper itself.

**Comment by icyflame** [comment]
You could have committed on the server (?)

anyway, you can fix it with `git config --add user.name "Harsh Gupta"` and `git config --add user.email your@email.com`. :slightly_smiling_face:

**Comment by hargup** [comment]
Fixed the email and wrote a small python wrapper over it. @icyflame please merge the PR if you think it is good enough.

**Comment by icyflame** [comment]
@hargup Thanks! Merged.

**Pull request merged**
